fix compilation error wrt/ CreodiasClient
[Exec Stream Pumper] ERROR scala_maven.ScalaCompileMojo - /var/lib/jenkins/workspace/eo-geotrellis-extensions_develop/openeo-geotrellis/src/main/scala/org/openeo/geotrellis/file/FileRDDFactory.scala:120: error: type mismatch;
[Exec Stream Pumper] ERROR scala_maven.ScalaCompileMojo -  found   : org.openeo.opensearch.backends.CreodiasClient.type
[Exec Stream Pumper] ERROR scala_maven.ScalaCompileMojo -  required: org.openeo.opensearch.OpenSearchClient
[Exec Stream Pumper] ERROR scala_maven.ScalaCompileMojo -     val openSearch: OpenSearchClient = CreodiasClient
[Exec Stream Pumper] ERROR scala_maven.ScalaCompileMojo -                                        ^