apply NODATA of 0 to integral cell types (#544)
* add some pointers for debugging #446

* quickfix gaps of zeroes for integral cell types without NODATA #446

* fixup! quickfix gaps of zeroes for integral cell types without NODATA #446

Was throwing away tiles with a NODATA cell type.

* remove debugging code that introduces additional jobs #446

java.lang.AssertionError: expected:<5> but was:<7>
	at org.openeo.geotrellis.layers.Sentinel2FileLayerProviderTest.testToSclDilationMaskOnS2TileEdge(Sentinel2FileLayerProviderTest.scala:600)

* add test #446

* fixup! add test #446

* cleanup #446

* adapt version and CHANGELOG #446

* directory is not mounted on Jenkins machines, use Artifactory instead #446

java.io.IOException: Exception while reading RasterSource /vitodata/vegteam_lcfm_features_2020/LCFM/LSF-ANNUAL/v100/blocks/34/T/FR/2020/L2A-BANDS/LCFM_LSF-ANNUAL_V100_2020_34TFR_001_L2A-BANDS.tif in collection https://stac.openeo.vito.be. Detailed message: /vitodata/vegteam_lcfm_features_2020/LCFM/LSF-ANNUAL/v100/blocks/34/T/FR/2020/L2A-BANDS/LCFM_LSF-ANNUAL_V100_2020_34TFR_001_L2A-BANDS.tif (No such file or directory). File does not exist: /vitodata/vegteam_lcfm_features_2020/LCFM/LSF-ANNUAL/v100/blocks/34/T/FR/2020/L2A-BANDS/LCFM_LSF-ANNUAL_V100_2020_34TFR_001_L2A-BANDS.tif.
	at org.openeo.geotrellis.layers.FileLayerProviderTest.writeToNetCDFAndCompare(FileLayerProviderTest.scala:1766)
	at org.openeo.geotrellis.layers.FileLayerProviderTest.testMultibandNoNoDataCOGViaSTAC(FileLayerProviderTest.scala:1741)
Caused by: java.io.FileNotFoundException: /vitodata/vegteam_lcfm_features_2020/LCFM/LSF-ANNUAL/v100/blocks/34/T/FR/2020/L2A-BANDS/LCFM_LSF-ANNUAL_V100_2020_34TFR_001_L2A-BANDS.tif (No such file or directory)
	at org.openeo.geotrellis.layers.FileLayerProviderTest.writeToNetCDFAndCompare(FileLayerProviderTest.scala:1766)
	at org.openeo.geotrellis.layers.FileLayerProviderTest.testMultibandNoNoDataCOGViaSTAC(FileLayerProviderTest.scala:1741)

* remove unnecessary mount again #446