Catalog API is allergic to overlapping polygons
org.openeo.geotrellissentinelhub.SentinelHubException: Sentinel Hub returned an error
response: HTTP/1.1 500 Internal Server Error with body: {"code":500,"description":"com.impossibl.postgres.jdbc.PGSQLSimpleException: GEOSIntersects: TopologyException: side location conflict at -4.1104655421087282 48.5454567696071"}
request: POST https://services.sentinel-hub.com/api/v1/catalog/search with body:
{
    "intersects": {"type":"MultiPolygon","coordinates":[[[[-0.9448890683345355,43.65752771574323],[-0.9480255323285457,43.56538480633614],[-1.0747514334934853,43.56758990643172],[-1.0718083693299232,43.6597398806271],[-0.9448890683345355,43.65752771574323]]],[[[-0.854668685481034,44.449740677776695],[-0.858034414368714,44.35761590697902],[-0.9864486873377145,44.359952764311224],[-0.9832843954791508,44.452085013290734],[-0.854668685481034,44.449740677776695]]],[[[-0.5958779358117919,43.80134867703532],[-0.59956520590433,43.70922994993894],[-0.7265649836425437,43.71182787083356],[-0.7230723737688886,43.80395491717009],[-0.5958779358117919,43.80134867703532]]],[[[-0.6305576413296994,44.38487194272289],[-0.6342663921642829,44.29276032854951],[-0.762520327416931,44.295345857212965],[-0.7590122180063582,44.387465744610246],[-0.6305576413296994,44.38487194272289]]],[[[-0.5988771554527041,43.249442809359536],[-0.6024896299185265,43.15731496134888],[-0.7283406266106817,43.15988424825091],[-0.7249173698996167,43.25202033317111],[-0.5988771554527041,43.249442809359536]]],[[[-0.5812012595457193,43.24896169078329],[-0.5848402506601661,43.15683503164735],[-0.7106886926974832,43.15942371041872],[-0.7072389052004916,43.25155866853706],[-0.5812012595457193,43.24896169078329]]],[[[-3.9723778881520104,48.5798371333794],[-3.9706155454817713,48.48772778908165],[-4.109175972014959,48.48647585051126],[-4.111189780096545,48.57858115917846],[-3.9723778881520104,48.5798371333794]]],[[[-1.3743752683034758,48.00801593281426],[-1.377262861366258,47.91592118644084],[-1.5142659713872195,47.917775826133706],[-1.511621940331238,48.009876536589594],[-1.3743752683034758,48.00801593281426]]],[[[-0.9674609742777565,43.62772158806831],[-0.9705597820902782,43.53557690079866],[-1.09722493603399,43.537755875101816],[-1.09431924205709,43.62990754395021],[-0.9674609742777565,43.62772158806831]]],[[[-0.5789333397390267,43.24392790869368],[-0.5825751011766165,43.15180132243178],[-0.7084130110735386,43.15439225799785],[-0.704960403224801,43.24652715056403],[-0.5789333397390267,43.24392790869368]]],[[[0.026155226571626135,43.672235184388214],[0.021535550879576194,43.58016180285496],[-0.10512966967570059,43.583442166467265],[-0.10070297887862734,43.67552604974049],[0.026155226571626135,43.672235184388214]]],[[[-0.8962209736982227,43.4614894158291],[-0.899409808896225,43.36934617973822],[-1.0257230666131545,43.3715973329169],[-1.022725669207925,43.463747783975684],[-0.8962209736982227,43.4614894158291]]],[[[-3.923499880795668,48.53812441953467],[-3.9218285645562605,48.44601310498359],[-4.06027766058636,48.44482072244561],[-4.062199883776363,48.53692819395821],[-3.923499880795668,48.53812441953467]]],[[[-0.5853350177663066,43.2508398013246],[-0.5889680314950774,43.15871289188312],[-0.7148206960173726,43.161297117527695],[-0.7113769063420464,43.25343231166274],[-0.5853350177663066,43.2508398013246]]],[[[-1.010246724123066,43.67027746347255],[-1.0132848310744806,43.57813104730519],[-1.140042327520492,43.58026428627419],[-1.1371977771612607,43.67241753710164],[-1.010246724123066,43.67027746347255]]],[[[-0.8389043211015376,44.491234619925734],[-0.8422996737979832,44.39911147385569],[-0.970803413708738,44.401467696373366],[-0.9676099243710714,44.49359838224251],[-0.8389043211015376,44.491234619925734]]],[[[-1.2486229616110682,48.669945161281476],[-1.2518068798957838,48.57786701751547],[-1.3905811770053473,48.57989079780118],[-1.3876497249266047,48.671975466057546],[-1.2486229616110682,48.669945161281476]]],[[[0.23466752712301628,46.40780087708629],[0.23931144111342634,46.31575050797047],[0.10647443279828203,46.31246350394863],[0.10160781070366318,46.40450335413976],[0.23466752712301628,46.40780087708629]]],[[[0.222343521421343,46.41157018269561],[0.22700872846567594,46.319520832802695],[0.09416402860760155,46.316219326993554],[0.08927607844290884,46.408258111606656],[0.222343521421343,46.41157018269561]]],[[[0.21631248393540742,45.525825003628626],[0.22084574297255805,45.433761808868255],[0.09009551081727786,45.43050307559299],[0.08534969575822494,45.522555850888416],[0.21631248393540742,45.525825003628626]]],[[[-0.6600636102924216,43.5136677525562],[-0.6636166774784095,43.42154009901425],[-0.7900190571828337,43.424054004900725],[-0.7866578237769929,43.516189713394745],[-0.6600636102924216,43.5136677525562]]],[[[-1.2517641316665693,48.66988411795535],[-1.2549423344011972,48.57780581907453],[-1.393716681487634,48.579825818712024],[-1.3907909457083731,48.67191062990345],[-1.2517641316665693,48.66988411795535]]],[[[-0.5850782428403065,43.246486371118124],[-0.5887110908244041,43.15435940878449],[-0.7145547974797981,43.156943714531366],[-0.711111131193424,43.2490789619004],[-0.5850782428403065,43.246486371118124]]],[[[-0.0669544431512408,43.596568794436685],[-0.07142030714700588,43.504486399962516],[-0.1979375214986768,43.50765947979841],[-0.19366395571326858,43.59975203487535],[-0.0669544431512408,43.596568794436685]]],[[[-4.041087275810993,48.546125990245656],[-4.039202647149997,48.45401804392219],[-4.177668107893512,48.452684288050484],[-4.179803714779287,48.544787935710445],[-4.041087275810993,48.546125990245656]]],[[[-0.9014547503931123,44.40795706609873],[-0.9047423233528317,44.31582883119517],[-1.0330691239305196,44.31811153869594],[-1.0299825750738607,44.41024707899764],[-0.9014547503931123,44.40795706609873]]],[[[-0.5789461943019552,43.24693536645602],[-0.5825883185757786,43.15480882789129],[-0.7084324011246186,43.157399889220684],[-0.7049794596054526,43.2495347344329],[-0.5789461943019552,43.24693536645602]]],[[[-0.11295222746837782,43.64321063382422],[-0.1173552683444272,43.55112523337248],[-0.24397501001509064,43.554250078470126],[-0.23976475986079923,43.6463454845667],[-0.11295222746837782,43.64321063382422]]],[[[-1.1037899298268623,44.32030856642568],[-1.1067515902761185,44.22816756338089],[-1.2349027693942258,44.230220219926515],[-1.2321413157661552,44.322367793504206],[-1.1037899298268623,44.32030856642568]]],[[[-0.31376674216455225,44.76932008003622],[-0.31802767775660307,44.67723716912845],[-0.44709664489171863,44.68019722318459],[-0.4430402071272257,44.772289600725806],[-0.31376674216455225,44.76932008003622]]]]},
    "datetime": "2021-04-01T00:00:00Z/2021-06-30T23:59:59.999999999Z",
    "collections": ["sentinel-1-grd"],
    "query": {},
}