fixed compile error
[Thread-5] ERROR scala_maven.ScalaCompileMojo - /var/lib/jenkins/workspace/eo-geotrellis-extensions_develop/geotrellis-common/src/main/scala/org/openeo/geotrelliscommon/OpenEORasterCube.scala:10: error: Symbol 'type org.apache.spark.rdd.RDD' is missing from the classpath.
[Thread-5] ERROR scala_maven.ScalaCompileMojo - This symbol is required by 'class geotrellis.spark.ContextRDD'.
[Thread-5] ERROR scala_maven.ScalaCompileMojo - Make sure that type RDD is in your classpath and check for conflicting dependencies with `-Ylog-classpath`.
[Thread-5] ERROR scala_maven.ScalaCompileMojo - A full rebuild may help if 'ContextRDD.class' was compiled against an incompatible version of org.apache.spark.rdd.
[Thread-5] ERROR scala_maven.ScalaCompileMojo - class OpenEORasterCube[K](rdd: RDD[(K, MultibandTile)], metadata: TileLayerMetadata[K],val openEOMetadata:OpenEORasterCubeMetadata) extends ContextRDD[K,MultibandTile,TileLayerMetadata[K]](rdd, metadata){
[Thread-5] ERROR scala_maven.ScalaCompileMojo -                                                                                                                                             ^
[Thread-5] ERROR scala_maven.ScalaCompileMojo - /var/lib/jenkins/workspace/eo-geotrellis-extensions_develop/geotrellis-common/src/main/scala/org/openeo/geotrelliscommon/OpenEORasterCube.scala:10: error: not found: type RDD
[Thread-5] ERROR scala_maven.ScalaCompileMojo - class OpenEORasterCube[K](rdd: RDD[(K, MultibandTile)], metadata: TileLayerMetadata[K],val openEOMetadata:OpenEORasterCubeMetadata) extends ContextRDD[K,MultibandTile,TileLayerMetadata[K]](rdd, metadata){
[Thread-5] ERROR scala_maven.ScalaCompileMojo -                                ^
[Thread-5] ERROR scala_maven.ScalaCompileMojo - two errors found