fix test failing because of more strict band link matching
java.lang.IllegalArgumentException: Could not find data for your load_collection request with catalog ID "Sentinel2". The catalog query had correlation ID "" and returned 2 results.
	at org.openeo.geotrellis.layers.FileLayerProviderTest.testCreoNonNativeProjection(FileLayerProviderTest.scala:961)