EP-3869: fixed another manifestation of java.util.concurrent.TimeoutException
scala> elasticsearchRepository.getGeometry("sentinel-hub-tiling-grid-1", "31UDS_7_2")
14 Sep 10:46:38 INFO [http.JavaClient$] - Creating HTTP client on https://es-apps-dev.vgt.vito.be:443
java.lang.ExceptionInInitializerError
	at com.sksamuel.elastic4s.ResponseHandler$.fromEntity(ResponseHandler.scala:34)
	at com.sksamuel.elastic4s.ResponseHandler$.fromResponse(ResponseHandler.scala:29)
	at com.sksamuel.elastic4s.requests.get.GetHandlers$GetHandler$$anon$2.good$1(GetHandlers.scala:59)
	at com.sksamuel.elastic4s.requests.get.GetHandlers$GetHandler$$anon$2.handle(GetHandlers.scala:62)
	at com.sksamuel.elastic4s.ElasticClient$$anonfun$execute$1.apply(ElasticClient.scala:36)
	at com.sksamuel.elastic4s.ElasticClient$$anonfun$execute$1.apply(ElasticClient.scala:35)
	at scala.util.Success$$anonfun$map$1.apply(Try.scala:237)
	at scala.util.Try$.apply(Try.scala:192)
	at scala.util.Success.map(Try.scala:237)
	at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:237)
	at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:237)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)
	at scala.concurrent.impl.ExecutionContextImpl$AdaptedForkJoinTask.exec(ExecutionContextImpl.scala:121)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Caused by: com.fasterxml.jackson.databind.JsonMappingException: Incompatible Jackson version: 2.10.2
	at com.fasterxml.jackson.module.scala.JacksonModule$class.setupModule(JacksonModule.scala:64)
	at com.fasterxml.jackson.module.scala.DefaultScalaModule.setupModule(DefaultScalaModule.scala:19)
	at com.fasterxml.jackson.databind.ObjectMapper.registerModule(ObjectMapper.java:808)
	at com.sksamuel.elastic4s.JacksonSupport$.<init>(JacksonSupport.scala:12)
	at com.sksamuel.elastic4s.JacksonSupport$.<clinit>(JacksonSupport.scala)
	... 17 more
java.util.concurrent.TimeoutException: Futures timed out after [60 seconds]
  at scala.concurrent.impl.Promise$DefaultPromise.ready(Promise.scala:219)
  at scala.concurrent.impl.Promise$DefaultPromise.result(Promise.scala:223)
  at scala.concurrent.Await$$anonfun$result$1.apply(package.scala:190)
  at scala.concurrent.BlockContext$DefaultBlockContext$.blockOn(BlockContext.scala:53)
  at scala.concurrent.Await$.result(package.scala:190)
  at com.sksamuel.elastic4s.ElasticApi$RichFuture.await(ElasticApi.scala:88)
  at org.openeo.geotrellissentinelhub.ElasticsearchRepository.getGeometry(ElasticsearchRepository.scala:92)
  ... 32 elided