remove debugging code that introduces additional jobs #446
java.lang.AssertionError: expected:<5> but was:<7>
	at org.openeo.geotrellis.layers.Sentinel2FileLayerProviderTest.testToSclDilationMaskOnS2TileEdge(Sentinel2FileLayerProviderTest.scala:600)