EP-3869: fixed java.util.concurrent.TimeoutException when querying Elasticsearch
JobTracker logs:
resuming with remaining jobs after failing to handle batch job b815972c-60fd-4b94-b068-5c1236f55fca:
Traceback (most recent call last):
  File "/opt/scripts/OpenEO/venv/lib64/python3.6/site-packages/openeogeotrellis/job_tracker.py", line 79, in update_statuses
    if self._batch_jobs.poll_sentinelhub_batch_processes(job_info):
  File "/opt/scripts/OpenEO/venv/lib64/python3.6/site-packages/openeogeotrellis/backend.py", line 615, in poll_sentinelhub_batch_processes
    caching_service.download_and_cache_results(bucket_name, subfolder, collecting_folder)
  File "/opt/scripts/OpenEO/venv/lib64/python3.6/site-packages/py4j/java_gateway.py", line 1310, in __call__
    answer, self.gateway_client, self.target_id, self.name)
  File "/opt/scripts/OpenEO/venv/lib64/python3.6/site-packages/py4j/protocol.py", line 328, in get_return_value
    format(target_id, ".", name), value)
py4j.protocol.Py4JJavaError: An error occurred while calling o1.download_and_cache_results.
: java.util.concurrent.TimeoutException: Futures timed out after [60 seconds]
	at scala.concurrent.impl.Promise$DefaultPromise.ready(Promise.scala:219)
	at scala.concurrent.impl.Promise$DefaultPromise.result(Promise.scala:223)
	at scala.concurrent.Await$$anonfun$result$1.apply(package.scala:190)
	at scala.concurrent.BlockContext$DefaultBlockContext$.blockOn(BlockContext.scala:53)
	at scala.concurrent.Await$.result(package.scala:190)
	at com.sksamuel.elastic4s.ElasticApi$RichFuture.await(ElasticApi.scala:88)
	at org.openeo.geotrellissentinelhub.ElasticsearchRepository.getGeometry(ElasticsearchRepository.scala:92)
	at org.openeo.geotrellissentinelhub.CachingService.org$openeo$geotrellissentinelhub$CachingService$$cacheTile$1(CachingService.scala:38)
	at org.openeo.geotrellissentinelhub.CachingService$$anonfun$download_and_cache_results$1.apply(CachingService.scala:58)
	at org.openeo.geotrellissentinelhub.CachingService$$anonfun$download_and_cache_results$1.apply(CachingService.scala:57)
	at org.openeo.geotrellissentinelhub.S3Service$$anonfun$downloadBatchProcessResults$1$$anonfun$apply$3$$anonfun$apply$5.apply(S3Service.scala:145)
	at org.openeo.geotrellissentinelhub.S3Service$$anonfun$downloadBatchProcessResults$1$$anonfun$apply$3$$anonfun$apply$5.apply(S3Service.scala:139)
	at scala.collection.TraversableLike$WithFilter$$anonfun$foreach$1.apply(TraversableLike.scala:733)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at scala.collection.TraversableLike$WithFilter.foreach(TraversableLike.scala:732)
	at org.openeo.geotrellissentinelhub.S3Service$$anonfun$downloadBatchProcessResults$1$$anonfun$apply$3.apply(S3Service.scala:139)
	at org.openeo.geotrellissentinelhub.S3Service$$anonfun$downloadBatchProcessResults$1$$anonfun$apply$3.apply(S3Service.scala:127)
	at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
	at org.openeo.geotrellissentinelhub.S3Service$$anonfun$downloadBatchProcessResults$1.apply(S3Service.scala:127)
	at org.openeo.geotrellissentinelhub.S3Service$$anonfun$downloadBatchProcessResults$1.apply(S3Service.scala:118)
	at org.openeo.geotrellissentinelhub.S3Service.withS3Client(S3Service.scala:30)
	at org.openeo.geotrellissentinelhub.S3Service.downloadBatchProcessResults(S3Service.scala:118)
	at org.openeo.geotrellissentinelhub.CachingService.download_and_cache_results(CachingService.scala:52)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:238)
	at java.lang.Thread.run(Thread.java:748)

A Scala REPL on dataflow revealed the root cause:
scala> val elasticsearchRepository = new ElasticsearchRepository("https://es-apps-dev.vgt.vito.be:443")
elasticsearchRepository: org.openeo.geotrellissentinelhub.ElasticsearchRepository = org.openeo.geotrellissentinelhub.ElasticsearchRepository@54d18072

scala> elasticsearchRepository.getGeometry("sentinel-hub-tiling-grid-1", "31UDS_7_2")
09 Sep 17:33:28 INFO [http.JavaClient$] - Creating HTTP client on https://es-apps-dev.vgt.vito.be:443
java.lang.NoClassDefFoundError: com/fasterxml/jackson/core/exc/InputCoercionException
	at com.fasterxml.jackson.module.scala.deser.NumberDeserializers$.<init>(ScalaNumberDeserializersModule.scala:51)
	at com.fasterxml.jackson.module.scala.deser.NumberDeserializers$.<clinit>(ScalaNumberDeserializersModule.scala)
	at com.fasterxml.jackson.module.scala.deser.ScalaNumberDeserializersModule$class.$init$(ScalaNumberDeserializersModule.scala:63)
	at com.fasterxml.jackson.module.scala.DefaultScalaModule.<init>(DefaultScalaModule.scala:18)
	at com.fasterxml.jackson.module.scala.DefaultScalaModule$.<init>(DefaultScalaModule.scala:35)
	at com.fasterxml.jackson.module.scala.DefaultScalaModule$.<clinit>(DefaultScalaModule.scala)
	at com.sksamuel.elastic4s.JacksonSupport$.<init>(JacksonSupport.scala:12)
	at com.sksamuel.elastic4s.JacksonSupport$.<clinit>(JacksonSupport.scala)
	at com.sksamuel.elastic4s.ResponseHandler$.fromEntity(ResponseHandler.scala:34)
	at com.sksamuel.elastic4s.ResponseHandler$.fromResponse(ResponseHandler.scala:29)
	at com.sksamuel.elastic4s.requests.get.GetHandlers$GetHandler$$anon$2.good$1(GetHandlers.scala:59)
	at com.sksamuel.elastic4s.requests.get.GetHandlers$GetHandler$$anon$2.handle(GetHandlers.scala:62)
	at com.sksamuel.elastic4s.ElasticClient$$anonfun$execute$1.apply(ElasticClient.scala:36)
	at com.sksamuel.elastic4s.ElasticClient$$anonfun$execute$1.apply(ElasticClient.scala:35)
	at scala.util.Success$$anonfun$map$1.apply(Try.scala:237)
	at scala.util.Try$.apply(Try.scala:192)
	at scala.util.Success.map(Try.scala:237)
	at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:237)
	at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:237)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)
	at scala.concurrent.impl.ExecutionContextImpl$AdaptedForkJoinTask.exec(ExecutionContextImpl.scala:121)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Caused by: java.lang.ClassNotFoundException: com.fasterxml.jackson.core.exc.InputCoercionException
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 25 more
java.util.concurrent.TimeoutException: Futures timed out after [60 seconds]
  at scala.concurrent.impl.Promise$DefaultPromise.ready(Promise.scala:219)
  at scala.concurrent.impl.Promise$DefaultPromise.result(Promise.scala:223)
  at scala.concurrent.Await$$anonfun$result$1.apply(package.scala:190)
  at scala.concurrent.BlockContext$DefaultBlockContext$.blockOn(BlockContext.scala:53)
  at scala.concurrent.Await$.result(package.scala:190)
  at com.sksamuel.elastic4s.ElasticApi$RichFuture.await(ElasticApi.scala:88)
  at org.openeo.geotrellissentinelhub.ElasticsearchRepository.getGeometry(ElasticsearchRepository.scala:92)
  ... 32 elided