fix confusing error wrt/ missing Accept-Ranges header
Redirect responses don't have this header but their targets do.

java.lang.IllegalArgumentException: requirement failed: Server doesn't support ranged byte reads
    at scala.Predef$.require(Predef.scala:281)
    at org.openeo.geotrellis.CustomizableHttpRangeReader.totalLength$lzycompute(CustomizableHttpRangeReader.scala:31)
    at org.openeo.geotrellis.CustomizableHttpRangeReader.totalLength(CustomizableHttpRangeReader.scala:10)
    at geotrellis.util.StreamingByteReader.ensureChunk(StreamingByteReader.scala:109)
    at geotrellis.util.StreamingByteReader.get(StreamingByteReader.scala:130)
    at geotrellis.raster.io.geotiff.reader.GeoTiffInfo$.read(GeoTiffInfo.scala:127)
    at geotrellis.raster.io.geotiff.reader.GeoTiffReader$.readMultiband(GeoTiffReader.scala:211)
    at geotrellis.raster.geotiff.GeoTiffRasterSource.$anonfun$tiff$1(GeoTiffRasterSource.scala:40)
    at scala.Option.getOrElse(Option.scala:189)
    at geotrellis.raster.geotiff.GeoTiffRasterSource.tiff$lzycompute(GeoTiffRasterSource.scala:37)
    at geotrellis.raster.geotiff.GeoTiffRasterSource.tiff(GeoTiffRasterSource.scala:34)
    at geotrellis.raster.geotiff.GeoTiffRasterSource.crs(GeoTiffRasterSource.scala:53)
    at geotrellis.raster.RasterSource.reprojectToRegion(RasterSource.scala:74)
    at org.openeo.geotrellis.icor.DEMProvider.<init>(DEMProvider.scala:16)
    at org.openeo.geotrellis.icor.AtmosphericCorrection.$anonfun$correct$1(AtmosphericCorrection.scala:66)
    at org.apache.spark.rdd.RDD.$anonfun$mapPartitions$2(RDD.scala:853)
    at org.apache.spark.rdd.RDD.$anonfun$mapPartitions$2$adapted(RDD.scala:853)