temporarily revert implementation because of failing testBIOMASS #67
openeo.rest.OpenEoApiError: [500] Internal: Server error: Job 1031 cancelled runaway job 1031 cancelled after PT15M (ref: r-a9e69bceb9d249a89331994a9509399d)

Looks like the combination of whole-world AgEra5 features and a -90/+90 day date shift of the BIOMASS process makes for a lot of SpaceTimeKeys.