convert tiffset'ed GeoTIFF to COG again
* convert tiffset'ed GeoTIFF to COG again #393

* clean up + basic test #393

* fix test #393

ERROR 1: /tmp/gdal_translate_to_COG_17685663456985683915.tif.tmp: Unable to export color table to GeoTIFF file.  Color tables can only be written to 1 band or 2 bands Byte or UInt16 GeoTIFF files.

* fix tests #393

org.opentest4j.AssertionFailedError: expected: <LatLng> but was: <latlong-CS>
	at org.openeo.geotrellis.file.ProbaVPyramidFactoryTest.writeS10GeoTiffs(ProbaVPyramidFactoryTest.scala:107)

* temporarily skip building SHub module #393

* debug CRS of output of gdal_translate #393

* trigger build (and try using Maven cache) #393

* PROJ_LIB is set in container now #393

* run in container with PROJ_LIB set #393

* at least log error disguised as warning #393

* cleanup #393

* remove interfering PROJ_LIB #393

https://jira.vito.be/browse/EP-3684

* point PROJ_LIB to that of container and enable additional tests #393

* limit PROJ_LIB to gdal_translate #393

Setting PROJ_LIB in the container messes up several Python modules.

* Revert "temporarily skip building SHub module #393"

This reverts commit 2a092c91abe0959952be44b47afd7baf30153aaa.

* configurable PROJ_LIB with default #393