update CglsPyramidFactoryTest #805
org.scalatest.exceptions.TestFailedException: The cellType property had value int16, instead of its expected value uint8, on object GeoTiffMultibandTile(74,112,1,int16)
	at org.scalatest.matchers.MatchersHelper$.indicateFailure(MatchersHelper.scala:392)
	at org.scalatest.matchers.should.Matchers$ShouldMethodHelperClass.shouldMatcher(Matchers.scala:7304)
	at org.scalatest.matchers.should.Matchers$AnyShouldWrapper.should(Matchers.scala:7347)
	at geotrellis.raster.testkit.RasterMatchers.assertRastersEqual(RasterMatchers.scala:262)
	at geotrellis.raster.testkit.RasterMatchers.assertRastersEqual$(RasterMatchers.scala:253)
	at org.openeo.geotrellis.file.CglsPyramidFactoryTest.assertRastersEqual(CglsPyramidFactoryTest.scala:35)
	at geotrellis.raster.testkit.RasterMatchers.assertRastersEqual(RasterMatchers.scala:251)
	at geotrellis.raster.testkit.RasterMatchers.assertRastersEqual$(RasterMatchers.scala:250)
	at org.openeo.geotrellis.file.CglsPyramidFactoryTest.assertRastersEqual(CglsPyramidFactoryTest.scala:35)
	at geotrellis.raster.testkit.RasterMatchers.assertRastersEqual(RasterMatchers.scala:248)
	at geotrellis.raster.testkit.RasterMatchers.assertRastersEqual$(RasterMatchers.scala:247)
	at org.openeo.geotrellis.file.CglsPyramidFactoryTest.assertRastersEqual(CglsPyramidFactoryTest.scala:35)
	at org.openeo.geotrellis.file.CglsPyramidFactoryTest.readOriginalGrid(CglsPyramidFactoryTest.scala:75)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)