add onnx dependencies to default Python 3.11 image for batch jobs on Terrascope
https://github.com/Open-EO/openeo-geotrellis-extensions/issues/563
https://github.com/Open-EO/openeo-geotrellis-extensions/issues/577

java.lang.NoClassDefFoundError: ai/onnxruntime/OrtEnvironment
	at org.openeo.geotrellis.corsa.package$.Env$lzycompute(package.scala:36)
	at org.openeo.geotrellis.corsa.package$.Env(package.scala:36)
	at org.openeo.geotrellis.corsa.package$.$anonfun$processWindowOnnx$1(package.scala:144)
	at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1708)
	at org.openeo.geotrellis.corsa.package$.processWindowOnnx(package.scala:143)
	at org.openeo.geotrellis.corsa.package$.compress(package.scala:85)
	at org.openeo.geotrellis.OpenEOProcesses.$anonfun$corsaCompressGeneric$2(OpenEOProcesses.scala:1162)
	at org.apache.spark.rdd.PairRDDFunctions.$anonfun$mapValues$3(PairRDDFunctions.scala:754)
	at scala.collection.parallel.IterableSplitter$Mapped.next(RemainsIterator.scala:463)
	at scala.collection.Iterator$$anon$6.hasNext(Iterator.scala:478)
	at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:601)
	at org.apache.spark.shuffle.sort.BypassMergeSortShuffleWriter.write(BypassMergeSortShuffleWriter.java:143)
	at org.apache.spark.shuffle.ShuffleWriteProcessor.write(ShuffleWriteProcessor.scala:57)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:111)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:54)
	at org.apache.spark.TaskContext.runTaskWithListeners(TaskContext.scala:171)
	at org.apache.spark.scheduler.Task.run(Task.scala:147)
	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$5(Executor.scala:647)
	at org.apache.spark.util.SparkErrorUtils.tryWithSafeFinally(SparkErrorUtils.scala:80)
	at org.apache.spark.util.SparkErrorUtils.tryWithSafeFinally$(SparkErrorUtils.scala:77)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:99)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:650)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: java.lang.ClassNotFoundException: ai.onnxruntime.OrtEnvironment
	... 25 more